name: http-server-deploy
run-name: ${{ github.actor }} is deploying with http-server
on: [push]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Serve Files
        uses: Eun/http-server-action@v1
        with:
          directory: ${{ github.workspace }}
          port: 8282
          no-cache: false
          index-files: |
            ["index.html", "index.htm"]